[project]
name = "frida-server"
version = "0.1.0"
description = ""
[project.scripts]
start = "run:main"
requires-python = ">=3.8"
dependencies = [
    "flask>=2.0.0",
    "frida>=16.0.0",
    "frida-tools>=12.0.0"
]
